[tool.poetry]
name = "python-se-hw4"
version = "0.1.0"
description = "First web project"
authors = ["Kate Kozachenko <kottya1995@ukr.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
